# --- Етап 1: Builder ---
FROM python:3.9-slim-bullseye AS builder

WORKDIR /builder

# Створення та активація віртуального середовища
RUN python -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

# Встановлення numpy<2
RUN pip install --no-cache-dir "numpy<2"

# Встановлення torch + torchvision для CPU
RUN pip install --no-cache-dir torch==1.13.1+cpu torchvision==0.14.1+cpu \
    -f https://download.pytorch.org/whl/torch_stable.html
RUN pip install --no-cache-dir pillow

# --- Етап 2: Runtime ---
FROM python:3.9-slim-bullseye

WORKDIR /app

# Копіювання тільки віртуального середовища з залежностями з етапу "builder"
COPY --from=builder /opt/venv /opt/venv

# Копіювання лише необхідних для роботи файлів
COPY inference.py .
COPY model.pt .
COPY imagenet_class_index.json .

# Вказівка Python з віртуального середовища
ENV PATH="/opt/venv/bin:$PATH"

# Команда для запуску
ENTRYPOINT ["python", "inference.py"]

# Приклад команди для запуску, якщо не передано аргументи
CMD ["images/dog.jpg"]
