replicaCount: 1

image:
  repository: ghcr.io/brem090/mlops-homework
  pullPolicy: IfNotPresent
  tag: "bf9ba663ce980f0b8b89a4f50bb94c2d50d8247c"

service:
  type: ClusterIP
  port: 8000
  targetPort: 8000

resources:
  limits:
    cpu: 400m
    memory: 500Mi
  requests:
    cpu: 250m
    memory: 300Mi

env:
  - name: MODEL_PATH
    value: "/app/models/model.pkl"
  - name: FEATURES_N
    value: "20"
  - name: ZSCORE_THRESHOLD
    value: "3.0"
  - name: PROBA_THRESHOLD
    value: "0.5"
  - name: LOG_LEVEL
    value: "INFO"

serviceMonitor:
  enabled: true
  interval: 30s
  path: /metrics

livenessProbe:
  httpGet:
    path: /health
    port: 8000
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /health
    port: 8000
  initialDelaySeconds: 5
  periodSeconds: 5
